### PR TITLE
Complete static site generator refactor

### LINKED ISSUE #48: 🛠 Refactor with static site generator
## Reasoning

The site is appropriately a static website but the pages are currently duplicated. Changing the layout, navigation, and maintaining consistency will be difficult as it grows.

## Proposal

Static site generator with templates

Benefits:
+ Pages authored as simple markdown
+ More easily maintainable
+ Ecosystem of plugins
+ Many open source developers know how to use them

Resources
+ https://www.staticgen.com/
+ One I contribute to is https://hexo.io

They are all compatible with Github Pages, Netlify(the current host), and S3 buckets.

---

Your thoughts?

### LINKED ISSUE #90: Remove .min.css and .map files
We should just generate these automatically on build instead of requiring that they be in the folder already.

### PR DESCRIPTION
**Pull request by kfichter**
This is the big one... Closes #48 and indirectly closes #90 

Requesting review from @barrasso @tcrowe @therevoltingx 

Completely revamps the website to use [Hexo](https://hexo.io/). I tried to duplicate the exact content on the existing website to avoid any problems. Tasks to be completed before merging:
- [x] Make sure contributors can pull, test, and build this branch.
- [x] Make sure the website works as expected on common browsers and device sizes.
- [x] Ensure all existing website content is included on this branch.
- [x] Rewrite the README.
- [ ] Clean up any CSS/JS that can be cleaned up easily.
- [x] Clean up file structure.
- [x] Remove any unnecessary data scripts.

### CODE REVIEW

**Comment by kfichter** [comment]
So @tcrowe I don't think we really need to use the github/medium data scripts. The RSS feed is probably fine for now, we can revisit that question later. What do you think?

**Comment by therevoltingx** [comment]
Site loads great, checking things out.

`npm test` currently failing at `/src/feeds/github.js:87` with: `ReferenceError: get is not defined`.

Not a big deal, but `/src` and `/source` are both used which is a bit confusing.

**Comment by kfichter** [comment]
@therevoltingx Agreed that the `src` and `source` file structure is not ideal. Let's change that.

**Comment by tcrowe** [comment]
It looks great @kfichter 👍🏼

For anyone who wants to test:

```sh
git clone -b static-site-refactor https://github.com/ethsociety/learn-plasma.git
cd learn-plasma
npm install
npm run dev
```

---

Lets remove the external data feeds experiment and other extraneous modules:

```sh
# delete data feeds scripts
git rm -rf src

# remove unused modules
npm rm async github-graphql-api hexo-toc request url-join xml2js
```

+ Delete `hexo-toc` section from `./_config.yml`

---

@kfichter I found some bugs. I don't think you're responsible for all of it but if you want we can put it in this PR. I haven't checked if I have push access so I am just commenting now rather than trying to fix it myself.

This needs a key in `./source/_data/en.yml` or else it gives the wrong URI:
https://github.com/ethsociety/learn-plasma/blob/static-site-refactor/themes/learn-plasma/layout/index.ejs#L74

This link `simple guide to opening your first issue` returns a `404`
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/learn/index.md#L36

`./plasma-mvp.html` ➡️`./mvp.html`
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/learn/framework.md#L106
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/learn/framework.md#L117

`../docs/plasma-cash.html` ➡️`./cash.html`
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/learn/debit.md#L28
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/learn/debit.md#L62
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/learn/debit.md#L79

In `./source/en/contact/index.md` this can be renamed to `index.html`
+ remove `_lpchecked` attribute
+ `required=""`  ➡️`required`
+ `autofocus=""`  ➡️`autofocus`

`merkle` ➡️`Merkle` x5
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/learn/compare.md#L43

`simulatneously` ➡️ `simultaneously`
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/learn/debit.md#L31

`recieving` ➡️ `receiving`
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/learn/debit.md#L52

`merkle proof` ➡️`Merkle Proof`
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/learn/mvp.md#L90

`Unfortuntely` ➡️ `Unfortunately`
https://github.com/ethsociety/learn-plasma/blame/static-site-refactor/source/en/research/index.md#L183

Uncomment this line:
https://github.com/ethsociety/learn-plasma/blob/static-site-refactor/source/index.html#L10

Theoretically since we have `autoprefixer` module we do not have to use browser prefix in our source:
https://github.com/ethsociety/learn-plasma/blob/static-site-refactor/themes/learn-plasma/src/index.styl#L58

**Comment by tcrowe** [comment]
Replace `./package.json` scripts section:

+ Removes `data-*` section
+ Fixes `npm test`

```json
"scripts": {
  "clean": "rm -rf public source/build themes/learn-plasma/source db.json debug.log",
  "setup": "mkdir -p public/build source/build themes/learn-plasma/source",
  "dev-gulp": "gulp dev || true",
  "dev-hexo": "nodemon -L -w scripts -w themes/learn-plasma/_config.yml --ext yml,js --exec hexo serve --debug || true",
  "dev": "NODE_ENV=development run-p setup dev-* || true",
  "prd-gulp": "NODE_ENV=production gulp prd",
  "prd-hexo": "NODE_ENV=production hexo gen",
  "prd": "run-s setup prd-*",
  "test-server": "http-server public -p 7783 -a 127.0.0.1 -s -c-1 & echo $! > .test-server-id",
  "test-blc": "sleep 1 && blc --exclude-external -r --requests 32 http://127.0.0.1:7783/en && kill `cat .test-server-id` && rm .test-server-id",
  "test": "npm run prd && run-p test-*"
}
```

**Comment by tcrowe** [comment]
Hey @kfichter it looks like you resolved a ton of issues!

If you make this `menu.Learn` vs. `menu.learn` it will resolve the last 404:
https://github.com/ethsociety/learn-plasma/blob/static-site-refactor/themes/learn-plasma/layout/index.ejs#L38

The i18n function is currently case sensitive.

If you want to try it: `npm test`

**Pull request merged**
