### PR TITLE
minor typo

### PR DESCRIPTION
**Pull request by AdvaithD**
Minor type
`patters` changed to `patterns`

### CODE REVIEW

**Comment by kfichter** [comment]
This commit looks a little complex (looks like some minor formatting made a lot of changes). Can we rebase this to master?

**Comment by kfichter** [comment]
Closing as fixed in #49

**Comment by AdvaithD** [comment]
My bad @kfichter my editor was messed up, didn't notice.

**Comment by kfichter** [comment]
No worries!

**Pull request closed without merging**
