### PR TITLE
Create generalized-plasma.md

### PR DESCRIPTION
**Pull request by Ro5s**
Per Issue #126; summarizing Kelvin Fichter article, "Why is EVM-on-Plasma hard?"

### CODE REVIEW

**Comment by therevoltingx** [comment]
Looks great to me!

Providing links to PlasmaVM research and related projects would be great as well.

👍

**Comment by Ro5s** [comment]
Cool -- thanks for reviewing! I'll try and track down some PlasmaVM links to fill out that section a bit more.

**Comment by barrasso** [comment]
LGTM 👌🏼 @Ro5s have you found any other PlasmaVM links to add before we merge this?

**Comment by Ro5s** [comment]
Hey @barrasso thanks reviewing. I have not found any additional PlasmaVM links, so I guess we can merge. I am also reviewing 'Plasma Leap' (not sure if that should get its own page, as well)

**Comment by kfichter** [comment]
@barrasso @Ro5s I never got around to writing more about Plasma VM so there aren't any links :-/ sorry about that.

**Comment by Ro5s** [comment]
@kfichter Sounds good! I'll try and knock out Plasma Leap adds over weekend.

**Comment by Ro5s** [comment]
Closing per updated pr (with plasma leap reference, links): https://github.com/ethsociety/learn-plasma/pull/132

**Pull request closed without merging**
