### PR TITLE
Static site starter kit

### PR DESCRIPTION
**Pull request by tcrowe**
How to test:

```sh
git clone -b static-site-hexo https://github.com/tcrowe/learn-plasma.git
cd learn-plasma
npm install

# request blog and github data
# (if you run this a lot github will bark at you for api rate limit)
npm run data

# watch during development, auto-refresh courtesy of browser-sync
npm run dev
open http://127.0.0.1:7781

# build for production
npm run prd

# experimental static site test
npm test
```

Detailed help is in the [readme](https://github.com/tcrowe/learn-plasma). Thank you!

### CODE REVIEW

**Comment by tcrowe** [comment]
Here's how I configured it on Netlify

screen shot 2018-09-17 at 7 37 34 pm

screen shot 2018-09-17 at 7 38 09 pm

**Comment by tcrowe** [comment]
Ah, ok. I've got audit disabled. (for better or worse)

Sometimes if we keep running `npm audit fix` over and over it eventually fixes some problems. Sometimes creates others.

**Comment by therevoltingx** [comment]
@tcrowe 

Ok sorry for the delay. Everything generally looks really good. I think the bulk of the work is to migrate the content to MD files and scaffold the rest of the site. As long as we have the MD files we can always change frameworks with little impact on the content so that's great.

My only overall concern is with the languages. I see that there is support for multiple language, but my concern is how to keep content in sync? We already see a lot of small edits being made to the content in the English pages. My concern is that content and language may go out of sync between translations a the original content is still being finalized.

**Comment by therevoltingx** [comment]
@tcrowe 

Anyway we can fix the audit errors by upgrading the packages?

**Comment by therevoltingx** [comment]
Running `npm run data` gives me `npm ERR! missing script: data`

After running:

```
npm install nodemon --save
npm install gulp-util --save
```

`npm run dev` ran successfully but now I see these issues in the browser:

screen shot 2018-09-30 at 1 07 56 pm

No CSS seems to load, but all the content is there.

**Comment by tcrowe** [comment]
Hi Miguel 👋

`my concern is how to keep content in sync?`

I think this assumes that we could or should keep the different language pages in sync. Another possibility is to allow people literate in each language to contribute to the degree to which they are interested in Plasma. In this way its up to each group to help one another and discuss Plasma in a way most relevant to them.

`Anyway we can fix the audit errors by upgrading the packages?`

I've looked into a lot of the audit messages. They can be relevant if you are running these modules in a production. Since we are generating static files we will not have any attack surface. If you are interested I would recommend opening up the audit pages and source to confirm or deny my assertion above.

So there are a few options. 1) Believe and prioritize the audit messages 2) disregard them 3) `npm config -g audit false` 4) keep running `npm audit fix` repeatedly until no more warnings come up or 5) some mix of all the above.

**Comment by therevoltingx** [comment]
@tcrowe 

Ok tried but got stuck with `index.css` and `index.js` not found (see attached screenshot.)
I tried reseting my branch and start from scratch but no luck.

Not sure why `npm run dev` is not properly generating those files.

**Comment by kfichter** [comment]
Hey sorry I've been running pretty slow on this PR, been quite busy lately. Going to try to see if I can work the CSS a little today.

**Comment by kfichter** [comment]
I'm going to go ahead and pull this in and start to make some edits. I noticed that we need to add `gulp-utils` and upgrade gulp to 4.0.0 to make things work.

**Comment by therevoltingx** [comment]
OMG finally got to work using `npm start`

Thanks @kfichter !

**Pull request merged**
